### ISSUE TITLE
Javascript error: `Bounds are not valid` when no data present

### ISSUE THREAD

**Issue by smillardHNTB** [SmartColumbusOS/discovery_ui#49]
As a OS user
When a dataset isn't available for me to work with 
I want to be aware of what is going on so that I don't become frustrated.

AC:
- Give the user a nicer message when the dataset is not ready to view yet.

(Long term, we may create a more elegant solution dealing with the temporary state of partially-ingested.)

When a dataset is added and no data is ingested, the dataset details page will not render and the following error is provided in the console:
```
bundle.js:53 Error: Bounds are not valid.
    at t.fitBounds (bundle.js:19)
    at t.n.componentDidMount (bundle.js:107)
    at Fa (bundle.js:53)
    at Ba (bundle.js:53)
    at bundle.js:53
    at Object.t.unstable_runWithPriority (bundle.js:62)
    at Ps (bundle.js:53)
    at Os (bundle.js:53)
    at Ts (bundle.js:53)
    at Ms (bundle.js:53)
fa @ bundle.js:53
bundle.js:101 uncaught at Ps Error: Bounds are not valid.
    at t.fitBounds (https://discovery.dev-smartos.com/bundle.js:19:28268)
    at t.n.componentDidMount (https://discovery.dev-smartos.com/bundle.js:107:95496)
    at Fa (https://discovery.dev-smartos.com/bundle.js:53:82397)
    at Ba (https://discovery.dev-smartos.com/bundle.js:53:85072)
    at https://discovery.dev-smartos.com/bundle.js:53:98279
    at Object.t.unstable_runWithPriority (https://discovery.dev-smartos.com/bundle.js:62:3194)
    at Ps (https://discovery.dev-smartos.com/bundle.js:53:98214)
    at Os (https://discovery.dev-smartos.com/bundle.js:53:97990)
    at Ts (https://discovery.dev-smartos.com/bundle.js:53:97335)
    at Ms (https://discovery.dev-smartos.com/bundle.js:53:96356)
```

**Comment by jakeprem** [comment]
This sounds similar to what we fixed in https://github.com/smartcitiesdata/react_discovery_ui/issues/86.

We created this card to help improve the experience: https://github.com/smartcitiesdata/react_discovery_ui/issues/88

**Comment by LtChae** [comment]
Should this be handled by disc_api's bounding box generation? I don't think we handle bounding boxes for zero-feature geojson at the moment.

**Comment by mcsearchin** [comment]
Closing this to play smartcitiesdata/discovery_api#278 and smartcitiesdata/react_discovery_ui#88
